fest: Wasza stara
Gwardia-Czapli/Grzybobranie pull request #11
Opened 2024-03-22 17:28 UTC by mokoszerosy

Patrzcie stara weszła na gita :o

2024-03-22 17:42 UTC, Norbiros requested changes

2024-03-22 17:42 UTC, Norbiros commented on README.md
> +Love mom.
W markdownie entery nie dzialaja normalnie. Musi byc chyba `\`na końcu linijki.

2024-03-22 21:07 UTC, goteusz-maszyk requested changes

2024-03-22 21:07 UTC, goteusz-maszyk commented on README.md
> +Love mom.
```suggestion
Patrzcie na wasz plik weszła WASZA STARA zaraz wam wszytskim szlaban da jak nie usuniecie tych anime postów itp.\
Get to work :).\
Love mom.
```

2024-03-22 21:07 UTC, Kubaryt requested changes

2024-03-22 21:07 UTC, Kubaryt commented on README.md
> +Love mom.
Kłamstfa, moja mama nigdy by tak nie opwiedziała

2024-03-23 10:39 UTC, mokoszerosy commented on README.md
> +Love mom.
ja nie rozumiem

2024-03-23 10:39 UTC, mokoszerosy commented on README.md
> +Love mom.
aha nie ważne
już rozumiem

2024-03-23 10:42 UTC, mokoszerosy commented
nwm coś zmieniłem coś pusznołem ale nwm nie dało się help

2024-03-23 12:11 UTC, goteusz-maszyk commented
1. czy na pewno zacommitowałeś
2. czy rzuca jakims bledem

2024-03-23 15:47 UTC, mokoszerosy commented
1. Na pewno zakomitówałem bo nie pokazuje mi zmian u mnie, a wysłałem
2. nie nie rzuca błedem

2024-03-23 15:50 UTC, goteusz-maszyk commented
zobacz na `git log` (w terminalu) u siebie

2024-03-23 15:52 UTC, mokoszerosy commented
to wypluwa: fatal: not a git repository (or any of the parent directories): .git

2024-03-23 15:52 UTC, mokoszerosy commented
nie ważne to trza w pychrmie wpisać

2024-03-23 15:53 UTC, mokoszerosy commented
pokazuje że coś się wysłało o 11:41 dzisiaj

2024-03-26 18:07 UTC, Kubaryt approved these changes

2024-03-26 18:19 UTC, Norbiros approved these changes

2024-03-26 20:01 UTC, merged