123
Gwardia-Czapli/Grzybobranie pull request #12
Opened 2024-03-23 09:00 UTC by Karmel2354

💀

2024-03-23 09:29 UTC, Norbiros approved these changes

2024-03-23 10:49 UTC, mokoszerosy approved these changes
Super kod 10/10.

2024-03-23 10:49 UTC, mokoszerosy commented on bruh.txt
> +nic tu nie ma
ok super kod 10/10

2024-03-23 10:49 UTC, mokoszerosy commented on README.md
> +// terrible photo
Super zdjęcie 10/10

2024-03-23 10:49 UTC, mokoszerosy commented on pl/bruh
> +nic tu nie ma
Super kod 10/10

2024-03-23 11:11 UTC, Kubaryt requested changes

2024-03-23 11:11 UTC, Kubaryt commented on README.md
> +// terrible photo
Komentarze w markdownie są takie jak w html czyli `<!--comment-->`, `//` nie wykomentowało tego

2024-03-23 11:58 UTC, goteusz-maszyk requested changes
jak mi oddadzą ownera to dam approve

2024-03-23 11:59 UTC, goteusz-maszyk requested changes, later dismissed

2024-03-23 11:59 UTC, goteusz-maszyk commented on README.md
> +// terrible photo
nie zgadzam się z tą opinią

2024-03-23 20:56 UTC, SevaTarasyuk commented on bruh.txt
> +nic tu nie ma
Gówniany kod. Rób wszystko od nowa

2024-03-23 21:02 UTC, tapczanek1321 requested changes, later dismissed
TRAGEDIA napisz od nowa.

2024-04-04 14:27 UTC, Sanielia approved these changes

2024-04-04 20:54 UTC, tapczanek1321 requested changes
no ladnie ladnie napisales

2024-04-04 20:55 UTC, tapczanek1321 approved these changes

2024-04-05 13:45 UTC, merged