First pull request
Gwardia-Czapli/Grzybobranie pull request #20
Opened 2024-04-02 15:40 UTC by SevaTarasyuk

sdsddsx

2024-04-02 15:43 UTC, Kubaryt requested changes

2024-04-02 15:43 UTC, Kubaryt commented on README.md
> +# +1
W pliku powinien być tylko 1 główny header, zmień na `##`

2024-04-04 19:43 UTC, SevaTarasyuk commented on README.md
> +# +1
zrobione👍

2024-04-04 19:54 UTC, Norbiros approved these changes

2024-04-04 20:12 UTC, Kubaryt approved these changes

2024-04-07 19:35 UTC, goteusz-maszyk approved these changes

2024-04-16 21:11 UTC, merged