Aaa a aa a
Gwardia-Czapli/Grzybobranie pull request #8
Opened 2024-03-20 22:25 UTC by hexxcatee

2024-03-20 22:31 UTC, tapczanek1321 requested changes

2024-03-20 22:31 UTC, tapczanek1321 commented on wazneinfo.md
> +kys :33
ale niemilo....

2024-03-20 22:31 UTC, tapczanek1321 commented on wazneinfo.md
> +I strzelam z akacza i kolejny zginął
prosze dodac backslash :33

2024-03-20 22:31 UTC, tapczanek1321 commented on wazneinfo.md
> +wypierdalaj dominik
kys blagam zrob to juz

2024-03-20 22:32 UTC, hexxcatee commented on wazneinfo.md
> +wypierdalaj dominik
uwu

> kys blagam zrob to juz

2024-03-20 22:33 UTC, tapczanek1321 commented on wazneinfo.md
> +wypierdalaj dominik
> uwu
> 
> > kys blagam zrob to juz

zartuje oczywiscie misiu pysiu <33

2024-03-20 22:34 UTC, hexxcatee commented on wazneinfo.md
> +wypierdalaj dominik
za pozno wlasnie zlatuje z budynku

2024-03-20 22:36 UTC, tapczanek1321 commented
**proszę jej tego NIE akceptować...**

2024-03-21 05:47 UTC, Norbiros requested changes

2024-03-21 05:47 UTC, Norbiros commented on wazneinfo.md
> +lubie anime dziefczynki i zapieradalsanie w genszin impakt
Ojojoj

2024-03-21 06:23 UTC, goteusz-maszyk commented on wazneinfo.md
> +I strzelam z akacza i kolejny zginął
O co chodI

2024-03-21 06:24 UTC, Norbiros commented on wazneinfo.md
> +I strzelam z akacza i kolejny zginął
Nikt nie wie

2024-03-21 06:25 UTC, Norbiros commented on wazneinfo.md
> +I strzelam z akacza i kolejny zginął
A ze w markdownie nie ma nowych lini i trzeba backslash albo <br>

2024-03-21 15:37 UTC, Kubaryt approved these changes
Biedny dominik

2024-03-21 16:02 UTC, closed without merging